import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import AllEvents from '../components/AllEvents'
import ContactUs from '../components/ContactUs'
import Hero from '../components/hero'
import Gallery from '../components/Gallery'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sports Society</title>
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Hero/>
      <Gallery/>
      <AllEvents/>
      <ContactUs/>  
    </>
  )
}
